server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tymaterialmanagementdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
